name: Bug report
description: Report a bug.
title: "BUG: <Please replace this text with a comprehensive title>"

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the time to file a bug report.
      **Please take a few minutes to try these steps before creating a new issue**:
      1) Check if the issue has already been brought up.
      2) Try upgrading to the latest version of Kilosort4.
      3) Check for relevant documentation at kilosort.readthedocs.io.
      4) If you are using SpikeInterface, please try running Kilosort by itself.
      5) Check that your data and probe look like they are loaded correctly in
         the Kilosort GUI.

- type: markdown
  attributes:
    value: >
      If the bug occurred during sorting, please also upload the kilosort.log
      file located in the results directory (v4.0.8 or later).
    
- type: textarea
  attributes: 
    label: "Describe the issue:"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Reproduce the bug:"
    description: >
      A short code example that reproduces the problem/missing feature,
      if applicable, or a description of how you encountered it.
    render: python
  
- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include the full statement of all error messages, if any.
    render: shell

- type: textarea
  attributes:
    label: "Version information:"
    description: >
      Version of python, Kilosort, operating system, and any other
      software versions you think might be relevant to the bug (e.g. CUDA toolkit).
  validations:
    required: true
