name: Installation issue
description: Report an issue with installation for Kilosort.
title: "INSTALLATION: <Please replace this text with a comprehensive title>"

body:
    
- type: textarea
  attributes: 
    label: "Describe the issue:"
    description: >
      Let us know what issues you are having with installation.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Provide environment info:"
    description: >
      Please run `conda info` (or the appropriate command for your environment
      manager) in your Kilosort environment in your terminal/anaconda
      prompt to let us know the versions of your packages.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Operating system information:"
    description: >
      Operating system and version.
  validations:
    required: true
  
